import { useLanguage } from '../i18n';
import { ThemeToggle } from '../theme';
import { SiteFooter } from './SiteFooter';

export function LandingPage() {
  const { language, setLanguage } = useLanguage();
  const english = language === 'en';
  const t = english ? { eyebrow: 'Human-assisted moderation', title: 'Put the right comments first.', body: 'Review Desk uses NLP signals to prioritize comments for human review. People keep the final decision.', demo: 'Try the demo', moderator: 'Moderator access', note: 'Public demo uses clearly labelled sample data until a YouTube API key is configured.', how: 'A safer review workflow', one: '1. Load a YouTube video', oneBody: 'Bring available comments through the official YouTube Data API.', two: '2. Prioritize with model signals', twoBody: 'Risk and uncertainty help reviewers decide what to inspect first.', three: '3. Decide with context', threeBody: 'A moderator reviews the full text before recording a decision.', lang: 'Español' } : { eyebrow: 'Moderación asistida', title: 'Prioriza los comentarios que necesitan atención.', body: 'Review Desk usa señales de NLP para ordenar comentarios para revisión humana. La decisión final siempre la toma una persona.', demo: 'Prueba aquí el demo', moderator: 'Acceso para moderadores', note: 'La demo pública muestra datos de ejemplo claramente etiquetados hasta configurar una clave de YouTube.', how: 'Un flujo de revisión trazable', one: '1. Carga un vídeo de YouTube', oneBody: 'Obtén los comentarios disponibles mediante la API oficial de YouTube Data.', two: '2. Prioriza con señales del modelo', twoBody: 'El riesgo y la incertidumbre ayudan a decidir qué revisar primero.', three: '3. Decide con contexto', threeBody: 'Una persona revisa el texto completo antes de registrar una decisión.', lang: 'English' };
  return <div className="landing-page"><header className="landing-header"><a className="brand landing-brand" href="/"><span className="brand-mark">R</span><span>Review Desk</span></a><div className="landing-nav"><button type="button" className="language-button" onClick={() => setLanguage(english ? 'es' : 'en')} aria-label={t.lang}>{t.lang}</button><ThemeToggle /><a href="/demo">{t.demo}</a><a href="/moderator">{t.moderator}</a></div></header><main className="landing-main"><section className="hero"><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.body}</p><div className="hero-actions"><a className="hero-primary" href="/demo">{t.demo}</a><a className="hero-secondary" href="/moderator">{t.moderator}</a></div><p className="landing-note">{t.note}</p></section><section className="workflow" aria-labelledby="workflow-title"><span className="eyebrow">{t.how}</span><h2 id="workflow-title">{t.how}</h2><div className="workflow-grid"><article><strong>{t.one}</strong><p>{t.oneBody}</p></article><article><strong>{t.two}</strong><p>{t.twoBody}</p></article><article><strong>{t.three}</strong><p>{t.threeBody}</p></article></div></section></main><SiteFooter /></div>;
}
