import { FormEvent, useState } from 'react';
import { useLanguage } from '../i18n';
import { ThemeToggle } from '../theme';
import { SiteFooter } from './SiteFooter';

interface LoginFormProps { loading: boolean; error?: string; onSubmit: (username: string, password: string) => void; }

export function LoginForm({ loading, error, onSubmit }: LoginFormProps) {
  const { language, setLanguage } = useLanguage();
  const english = language === 'en';
  const t = english ? { back: 'Back to home', eyebrow: 'Review Desk · Moderators', title: 'Sign in', intro: 'Access your moderation queue to review risk signals with human context.', user: 'Username', password: 'Password', required: 'Enter your username and password to continue.', submit: loading ? 'Signing in…' : 'Sign in', demo: 'Try the public demo', hint: 'Clearly labelled sample data; no account needed.', lang: 'Español' } : { back: 'Volver al inicio', eyebrow: 'Review Desk · Moderadores', title: 'Inicia sesión', intro: 'Accede a tu cola de moderación para revisar las señales de riesgo con contexto humano.', user: 'Usuario', password: 'Contraseña', required: 'Escribe tu usuario y contraseña para continuar.', submit: loading ? 'Entrando…' : 'Entrar', demo: 'Prueba aquí el demo público', hint: 'Datos de ejemplo etiquetados; no necesitas una cuenta.', lang: 'English' };
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [validationError, setValidationError] = useState<string>();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!username.trim() || !password) { setValidationError(t.required); return; } setValidationError(undefined); onSubmit(username.trim(), password); }
  return <div className="auth-shell"><header className="site-header"><a className="brand" href="/" aria-label={t.back}><span className="brand-mark">R</span><span>Review Desk</span></a><nav className="site-nav" aria-label={english ? 'Main navigation' : 'Navegación principal'}><a href="/demo">{t.demo}</a><ThemeToggle /><button type="button" className="language-button" onClick={() => setLanguage(english ? 'es' : 'en')} aria-label={t.lang}>{t.lang}</button></nav></header><main className="login-page"><section className="login-card" aria-labelledby="login-title"><span className="eyebrow">{t.eyebrow}</span><h1 id="login-title">{t.title}</h1><p className="login-intro">{t.intro}</p><form onSubmit={submit} noValidate><div className="field"><label htmlFor="username">{t.user}</label><input id="username" name="username" type="text" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} disabled={loading} aria-invalid={Boolean(validationError || error)} aria-describedby={validationError || error ? 'login-error' : undefined} /></div><div className="field"><label htmlFor="password">{t.password}</label><input id="password" name="password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={loading} aria-invalid={Boolean(validationError || error)} aria-describedby={validationError || error ? 'login-error' : undefined} /></div>{(validationError || error) && <p id="login-error" className="form-error" role="alert">{validationError || error}</p>}<button className="primary-button" type="submit" disabled={loading}>{t.submit}</button></form><a className="demo-entry" href="/demo">{t.demo}</a><p className="demo-entry-hint">{t.hint}</p></section></main><SiteFooter /></div>;
}
