import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiError, currentUser, loadQueue, login, logout } from './api/client';
import { CommentDetailPanel } from './components/CommentDetailPanel';
import { LoginForm } from './components/LoginForm';
import { QueueItemCard } from './components/QueueItemCard';
import { StatusMessage } from './components/StatusMessage';
import type { PublicUser, QueueItem } from './types/moderation';
import './styles.css';
interface Session { token: string; user: PublicUser; }
export default function App() {
  const [session, setSession] = useState<Session>(); const [loginState, setLoginState] = useState<'idle' | 'loading'>('idle'); const [loginError, setLoginError] = useState<string>();
  const [comments, setComments] = useState<QueueItem[]>([]); const [loadState, setLoadState] = useState<'idle' | 'loading' | 'ready' | 'error' | 'unauthorized'>('idle'); const [queueError, setQueueError] = useState<string>(); const [selectedId, setSelectedId] = useState<string>();
  const selectedComment = comments.find((comment) => comment.comment_id === selectedId); const pendingCount = useMemo(() => comments.filter((comment) => comment.status === 'PENDING').length, [comments]); const orderedComments = useMemo(() => [...comments].sort((a, b) => b.risk_score - a.risk_score), [comments]);
  const fetchQueue = useCallback(async (token: string) => { setLoadState('loading'); setQueueError(undefined); try { const page = await loadQueue(token); setComments(page.items); setSelectedId(page.items[0]?.comment_id); setLoadState('ready'); } catch (error) { if (error instanceof ApiError && error.status === 401) { setSession(undefined); setComments([]); setLoadState('unauthorized'); return; } setQueueError(error instanceof Error ? error.message : 'No se pudo cargar la cola.'); setLoadState('error'); } }, []);
  async function handleLogin(username: string, password: string) { setLoginState('loading'); setLoginError(undefined); try { const response = await login(username, password); setSession({ token: response.access_token, user: response.user }); setLoginState('idle'); await fetchQueue(response.access_token); } catch (error) { setLoginState('idle'); setLoginError(error instanceof Error ? error.message : 'No se pudo iniciar sesión.'); } }
  const handleLogout = useCallback(async () => { const token = session?.token; setSession(undefined); setComments([]); setSelectedId(undefined); setLoadState('idle'); if (token) { try { await logout(token); } catch { /* Always clear the local session. */ } } }, [session?.token]);
  useEffect(() => { if (session) void currentUser(session.token).catch((error: unknown) => { if (error instanceof ApiError && error.status === 401) void handleLogout(); }); }, [session, handleLogout]);
  if (!session) return <LoginForm loading={loginState === 'loading'} error={loginError} onSubmit={handleLogin} />;
  return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Review Desk, inicio"><span className="brand-mark">R</span><span>Review Desk</span></a><div className="topbar-actions"><span className="environment-label">{session.user.display_name}</span><button className="logout-button" type="button" onClick={() => void handleLogout()}>Cerrar sesión</button></div></header><main className="workspace"><div className="page-heading"><div><span className="eyebrow">Moderación asistida</span><h1>Cola de revisión</h1><p className="intro">Trabaja primero los casos con mayor señal de riesgo. La puntuación orienta tu atención; tú tomas la decisión final.</p></div><div className="pending-count"><strong>{pendingCount}</strong><span>pendientes</span></div></div><div className="notice"><span aria-hidden="true">i</span><p><strong>Control humano:</strong> el riesgo estimado no es una verdad ni una acción automática. La incertidumbre señala cuándo conviene mirar con más contexto.</p></div><div className="workspace-grid"><section className="queue-panel" aria-labelledby="queue-title"><div className="section-heading"><div><h2 id="queue-title">Comentarios priorizados</h2><p>{orderedComments.length} casos · ordenados por riesgo estimado</p></div><span className="sort-label">Mayor riesgo primero</span></div><div className="queue-list">{loadState === 'loading' && <StatusMessage title="Cargando cola">Estamos consultando los casos pendientes.</StatusMessage>}{loadState === 'error' && <><StatusMessage title="No se pudo cargar la cola" tone="error">{queueError}</StatusMessage><button className="retry-button" type="button" onClick={() => void fetchQueue(session.token)}>Reintentar</button></>}{loadState === 'unauthorized' && <StatusMessage title="Sesión no autorizada">Tu sesión ya no es válida. Inicia sesión de nuevo.</StatusMessage>}{loadState === 'ready' && (orderedComments.length ? orderedComments.map((comment) => <QueueItemCard key={comment.comment_id} item={comment} selected={comment.comment_id === selectedId} onSelect={() => setSelectedId(comment.comment_id)} />) : <StatusMessage title="No hay comentarios pendientes">La cola está vacía por ahora.</StatusMessage>)}</div></section><section aria-label="Resumen del caso"><CommentDetailPanel comment={selectedComment} /></section></div></main><footer className="footer">Risk score = señal de priorización · Sin decisiones automáticas contra comentarios</footer></div>;
}
